namespace DDONamedGearPlanner
{
	public static class ItemFilterSettings
	{
		public static SlotType Slots;
		public static bool BodyCloth;
		public static bool BodyLight;
		public static bool BodyMedium;
		public static bool BodyHeavy;
		public static bool BodyDocent;
		public static bool OffhandShieldBuckler;
		public static bool OffhandShieldSmall;
		public static bool OffhandShieldLarge;
		public static bool OffhandShieldTower;
		public static bool OffhandShieldOrb;
		public static bool OffhandRuneArm;
		public static bool WeaponSimpleClub;
		public static bool WeaponSimpleQuarterstaff;
		public static bool WeaponSimpleDagger;
		public static bool WeaponSimpleSickle;
		public static bool WeaponSimpleLightMace;
		public static bool WeaponSimpleHeavyMace;
		public static bool WeaponSimpleMorningstar;
		public static bool WeaponSimpleLightXbow;
		public static bool WeaponSimpleHeavyXbow;
		public static bool WeaponMartialHandaxe;
		public static bool WeaponMartialBattleAxe;
		public static bool WeaponMartialGreatAxe;
		public static bool WeaponMartialKukri;
		public static bool WeaponMartialShortSword;
		public static bool WeaponMartialLongSword;
		public static bool WeaponMartialGreatSword;
		public static bool WeaponMartialScimitar;
		public static bool WeaponMartialFalchion;
		public static bool WeaponMartialRapier;
		public static bool WeaponMartialLightPick;
		public static bool WeaponMartialHeavyPick;
		public static bool WeaponMartialLightHammer;
		public static bool WeaponMartialWarHammer;
		public static bool WeaponMartialMaul;
		public static bool WeaponMartialGreatClub;
		public static bool WeaponMartialShortBow;
		public static bool WeaponMartialLongBow;
		public static bool WeaponExoticBastardSword;
		public static bool WeaponExoticDwarvenWarAxe;
		public static bool WeaponExoticKama;
		public static bool WeaponExoticKhopesh;
		public static bool WeaponExoticHandwraps;
		public static bool WeaponExoticRuneArm;
		public static bool WeaponExoticGreatXbow;
		public static bool WeaponExoticRepeatLightXbow;
		public static bool WeaponExoticRepeatHeavyXbow;
		public static bool WeaponThrowingAxe;
		public static bool WeaponThrowingDagger;
		public static bool WeaponThrowingHammer;
		public static bool WeaponThrowingDart;
		public static bool WeaponThrowingShuriken;
	}
}
